### PR TITLE
Added autoCreate: lazy

### PR DESCRIPTION
**Pull request by bckp**
It will declare Exchanges and Queues only after connection is established (eg: you try to use it)

### CODE REVIEW

**Comment by bckp** [comment]
So far i did not notice any issue, but I will be happy if someone else try this code too... Docs update will be ready tomorow

**Comment by f3l1x** [comment]
Looks good to me. WDYT @paveljanda? 

Can you add some basic test @bckp?

**Comment by paveljanda** [comment]
Agree, tests would be perfect. Also, there should be some info about that in the docs. Thx

**Comment by bckp** [comment]
OK, will wrote some tests and add docs, kind of busy now, but i will work on it ASAP :)

**Comment by f3l1x** [comment]
Any tests incoming? :-)

**Comment by bckp** [comment]
Well, kind busy... but Mallgroup/RabbitMQ with this is 7times faster then Contributte/RabbitMQ on requests!

**Comment by paveljanda** [comment]
That is perfect. :) Could you add some docs and preferably the tests as requested before? Thanks 🙌

**Comment by f3l1x** [comment]
How about finish this task? :-)

**Comment by bckp** [comment]
I will try during christmas... we are few versions ahead right now, so i need to sort things out first, so i can create more MR.

**Comment by bckp** [comment]
Hehe, i deleted that repository, cant add tests :/

**Comment by f3l1x** [comment]
What do you suggest @bckp?

**Comment by bckp** [comment]
Currently, I am working on 10.x-dev branch, it is based on your master, i removed Nette 2.4 support, switched to Nette/Schema in DI, added some of our fixes, SSL support, currently working on Federation support, when I will have this release ready, i will create MR, so we can be in SYNC again, is that good for you @f3l1x @paveljanda ?

**Pull request closed without merging**
