### PR TITLE
SSL support

### PR DESCRIPTION
**Pull request by radimvaculik**
See https://github.com/jakubkulhan/bunny/commit/f003f8319a770585e8f9a0e9b0290e9ce12f444f

### CODE REVIEW

**Comment by paveljanda** [comment]
Can you pls add something to the readme? What's possible ssl value? Bool, string, int..?

**Comment by radimvaculik** [comment]
@paveljanda Amended.

**Comment by paveljanda** [comment]
Thx

**Comment by radimvaculik** [comment]
@paveljanda Could you tag it as new release, please? Thanks.

**Pull request merged**
